title: Ty Schultz's Portfolio
description: This portfolio exhibits my work and experience from my time in university, internships, and personal projects.
theme: just-the-docs
nav_enabled: false

url: https://tsschultz.github.io/

aux_links:
  Home Page: https://tsschultz.github.io/
  LinkedIn: https://www.linkedin.com/in/ty-schultz/
  Github: https://github.com/tsschultz
